---
- hosts: all
  sudo_user: isucon
  sudo: yes
  tasks:
    - command: git clone https://github.com/tagomoris/xbuild.git /home/isucon/.xbuild
      args:
        creates: /home/isucon/.xbuild/ruby-install
    # python
    - command: /home/isucon/.xbuild/python-install 2.7.8 /home/isucon/.local/python
      args:
        creates: /home/isucon/.local/python/bin/python
    - command: /home/isucon/env.sh pip install gunicorn Flask MySQL-python
      args:
        creates: /home/isucon/.local/python/bin/gunicorn
